apiVersion: v1
kind: Service
metadata:
  name: diplom-web-app-service
  labels:
    app: diplom-web-app
spec:
  selector:
    app: diplom-web-app
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
